### PR TITLE
Fix AI GasMask Wearing

### LINKED ISSUE #3982: [Bug]:Visitors removing gas masks while in toxic environments
**Specifications**

Rimworld version: 1.5
Combat Extended version: 15.6.3.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list: 

Harmony
RimWorld
RimWorld - Royalty
RimWorld - Ideology
RimWorld - Biotech
RimWorld - Anomaly
Combat Extended

**Description**
Non-colonist pawns will remove gas masks while being in a completely polluted map, even if they spawned in with them. If a dev command is used to force them to wear a mask, they remove it after a delay, and said delay is variable. Presumably some script is running to remove the mask after X amount of time. I'm assuming this is a bug or at the very least a mistake in gameplay design, because it seems advisable to use the item Biotech added to resist pollution, in order to resist the toxic buildup from the environment. They will continue wearing cloth face coverings, just not gas masks. This not an environment without toxic buildup, they do eventually receive the condition.

This does not occur when running the game without CE. I encountered this bug in a larger modlist, and narrowed the list down for this ticket. Hence the mention of missing entries in the attached log, some spawn commands were in my palette.

**Expected behavior**
I expect visitors like caravans, to continue to wear gas masks in a 100% pollution environment. At the very least, if they are to remove their masks when they no longer need it, they would do so indoors.

**To reproduce**
Spawn a caravan onto a polluted map, and force someone in it to wear a gas mask. This was done both with the devmode quick start, and by actually landing on a polluted tile.

**Screenshots & log dumps**

Player-prev.log (Player.log is not a CE attempt)
https://pastebin.com/Yv4Hu6YU

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by ViralReaction**
## Additions

Describe new functionality added by your code, e.g.
- Tweaks AI of non-colonists to don gas masks when exposed to Toxic Gas
- Tweaks AI of non-colonists to don gas masks when exposed to Toxic Fallout
- Tweaks AI of non-colonists to don gas masks when exposed to Polluted Terrain

## Changes

Describe adjustments to existing features made in this merge, e.g.
- Refactor CompGasMask for minor performance improvements and readability
- Smoke checks for if pawn is Humanlike and not Subhuman. Prevents TryGetComp unnecessarily

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #3982 

## Reasoning

Why did you choose to implement things this way, e.g.
- Harmony patches before their target method to mimic Smoke and prevent ill effects
- Removing LINQ prevents unnecessary allocations
- Removes unnecessary null checks on apparel.def
- Consolidates checks to prevent unnecessary assignments of variables
- AI pawns will take off gas masks if they have them when spawning into map, but will put them back on if they are exposed. Would have to add additional checks to prevent this, but should not take them back off once donned by the new patches.

## Alternatives

Describe alternative implementations you have considered, e.g. 
- Allow player colonists to automatically wear gas masks if they have one
- Pawns utilize apparel wearing JobDriver

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [ ] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

File: Source/CombatExtended/Harmony/Harmony_GameCondition_ToxicFallout.cs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+            public static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions, ILGenerator generator)
+            {
+                List<CodeInstruction> codes = instructions.ToList();
+
+                MethodInfo targetMethod = AccessTools.Method(typeof(ToxicUtility), nameof(ToxicUtility.DoPawnToxicDamage));
+                MethodInfo additionalMethod = AccessTools.Method(typeof(Harmony_ToxicUtility), nameof(Harmony_ToxicUtility.TryNotify_ShouldEquipGasMask));
+                for (int i = 0; i < codes.Count; i++)
+                {
+
+                    if (codes[i].opcode == OpCodes.Call && codes[i].operand as MethodInfo == targetMethod)
```
Comment (mszabo-wikia) [inline Source/CombatExtended/Harmony/Harmony_GameCondition_ToxicFallout.cs]: nit: this and the below loop can use `codes[i].Calls(...)`

Comment (ViralReaction) [reply Source/CombatExtended/Harmony/Harmony_GameCondition_ToxicFallout.cs]: Put in your suggestion and had to fix IL slightly

**Review by mszabo-wikia — DISMISSED** [review]

**Review by N7Huntsman — APPROVED** [review]
