### PR TITLE
Fix Duplicate Float Menu

### LINKED ISSUE #938: [Bug]: Two options for picking up items in caravan maps
**Specifications**
Rimworld version: 1.3.3080
Combat Extended version: 1.3.4.0.1
Combat Extended source (Steam, GitHub, etc.): GitHub
Operating system: Windows 10
Mod list:
- brrainz.harmony
- ludeon.rimworld
- unlimitedhugs.hugslib
- ceteam.combatextended
- georodin.setupcamp

**Description**
Selecting a pawn and right clicking items in caravan maps (camps, ambushes, item stashes, etc.) has two pairs of "pick up {thing}..." and "pick up {thing} x{amount} (all)" commands.

**Expected behavior**
One pair of "pick up {thing}..." and "pick up {thing} x{amount} (all)" commands.

**To reproduce**
1. Start a new game with any scenario, world settings, landing spot and starting colonists;
2. Order at least one of the starting colonists to caravan out of the starting colony;
3. Move two tiles in any direction, enough to set up a camp using "Set Up Camp" (OR make an ambush incident with development mode);
4. Spawn in an item with development mode;
5. Select a colonist and right click on that item.

**Screenshots & log dumps**
Orders for pemmican with a selected pawn on an ambush caravan event map:
image
Orders for pemmican with a selected pawn on a colony map:
image

**I verify that I have done the following:**
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### LINKED ISSUE #1277: [Bug]: Pick up item right click option is doubled for drugs and medicine.
**Specifications**
Please provide the following.

Rimworld version: 
Combat Extended version: 1.3.4.4hf1, latest
Combat Extended source (Steam, GitHub, etc.): Git
Your operating system: Win10
Your mod list: https://gist.github.com/278aec420493e13139faa9becf592dcb

**Description**
Possibly related to #938 
Ordering a pawn to right click any item from drug or medicine category shows a menu with two identical "Pick up..." options - not including "Pick up ... (all)" 

**Expected behavior**
One "Pick up..." and one "Pick up...(all)" 

**To reproduce**
Create a new Crashlanded colony in dev mode with Hugslib option, select a pawn, right click medicine.

**Screenshots & log dumps**
image

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by ViralReaction**
## Changes

Describe adjustments to existing features made in this merge, e.g.
- Fixes duplicate float menu while on ambush map
image

## Reasoning

Why did you choose to implement things this way, e.g.
- Forcing true bypasses vanilla float menu without removing it's code

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #938 
- Closes #1277

## Alternatives

Describe alternative implementations you have considered, e.g.
- Duplicate float menu

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] Playtested a colony (Tested on home map and ambush)

### CODE REVIEW

File: Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs [hunk 1]
```diff
@@ -218,6 +218,28 @@ static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> inst
...
+                if (
+                    codes[i].opcode == OpCodes.Endfinally &&
+                    codes[i + 1].opcode == OpCodes.Ldloc_0 &&
+                    codes[i + 3].Calls(formingCaravan) &&
+                    codes[i + 4].opcode == OpCodes.Brtrue &&
+                    codes[i + 5].opcode == OpCodes.Ldloc_0)
+                {
+                    codes[i + 3].opcode = OpCodes.Ldc_I4_1;
+                    codes[i + 3].operand = null;
+                    foundCaravanInjection = true;
```
Comment (perkinslr) [inline Source/CombatExtended/Harmony/Harmony_FloatMenuMakerMap.cs:236]: Would be better to `break;` here after finding the correct target, to avoid continuing the search (and potentially finding an invalid second target when RW upstream updates). Otherwise, it's probably worth logging the number found, so if it changes we know something is up.

**Review by perkinslr — DISMISSED** [review]

**Review by perkinslr — APPROVED** [review]

**Review by N7Huntsman — APPROVED** [review]
