### PR TITLE
Fix mortar ammo change for sieges

### LINKED ISSUE #672: [Bug]: Siege broken due to Mortar not loading new shell types.
**Specifications**

Rimworld version:
Combat Extended version: Latest
Your operating system: Win10
Your mod list: just ce

**Description**
If Siege spawn in with different shell types, such as incendiary and HE, siegers will fire all the HE shells but refuse to fire the incendiary shells.
Causing the mortars to sop firing indefinitely, during this no additional shells will be dropped.

**Expected behavior**
Mortars continue to fire incendiary after HE shells are used up.

**To reproduce**
Spawn in a siege

**Screenshots & log dumps**

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by LockdownX7**
## Changes
- Fix turret reloading to automatically pick new ammo types only for non-player factions, not the other way around.

## References
- Closes #672

### CODE REVIEW

**Comment by LockdownX7** [comment]
Assembly file: 
[CombatExtended.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/6623221/CombatExtended.zip)

**Comment by Breadbox2k19** [comment]
Jolly, testing it rn

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
~~While this does allow raiders to use other types of shells when out of HE, colonists will also automatically change to different shells, which is not a desired behavior.~~

**Review by N7Huntsman — APPROVED** [review]
Apologies, I misspoke. In the *current* dev branch, colonists will automatically swap. With these changes, they will not, as desired. Raiders will swap, however, as desired.

File: Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs [hunk 1]
```diff
@@ -130,7 +130,7 @@ private static Thing FindBestAmmo(Pawn pawn, Building_Turret turret)
 			var ammoComp = turret.GetAmmo();
 			AmmoDef requestedAmmo = ammoComp.SelectedAmmo;	
 			var bestAmmo = FindBestAmmo(pawn, requestedAmmo);   // try to find currently selected ammo first
-			if (bestAmmo == null && ammoComp.EmptyMagazine && requestedAmmo.AmmoSetDefs != null && turret.Faction == Faction.OfPlayer)
+			if (bestAmmo == null && ammoComp.EmptyMagazine && requestedAmmo.AmmoSetDefs != null && turret.Faction != Faction.OfPlayer)
```
Comment (MadaraUchiha) [inline Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs:133]: How does this affect your own mortars' reloading?

Comment (N7Huntsman) [reply Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs:133]: From testing,  raiders will automatically change ammo types if they run out, but colonists will not. I consider this to be the desired behavior.

Comment (LockdownX7) [reply Source/CombatExtended/CombatExtended/Jobs/Utils/JobGiverUtils_Reload.cs:133]: Player faction turrets don't automatically change ammo types, as was the plan in 7a0a7cb91d6e0b7ca77c91d2b8239b1cf10de0c2.
