### PR TITLE
Fix Ammo Reloading

### LINKED ISSUE #4136: [Bug]: Incorrect ammo switching when magazine aren't full
**Specifications**
Rimworld version 1.6
Combat Extended Dev Snapshot

**Description**
Example:
An pawn has an assualt rifle with 20 FMJ in the magazine and 16 hollowpoints in the inventory.
If I tell him to switch to hollowpoints, he'll reload and end up with 46 rounds of FMJ in the assualt rifle.

**Expected behavior**
It'll have 16 hollowpoints in the magazine.

**To reproduce**
Any

**Screenshots & log dumps**
To be added soon

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by ViralReaction**
## Changes

Describe adjustments to existing features made in this merge, e.g.
- Adds check to see if magazine has ammo, if so will only check for same ammo

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #4136 

## Reasoning

Why did you choose to implement things this way, e.g.
- Fixing issue stemming from #3450

## Alternatives

Describe alternative implementations you have considered, e.g.
- Magic ammo type swapping

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

File: Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs [hunk 1]
```diff
@@ -831,7 +831,16 @@ public bool TryFindAmmoInInventory(out Thing ammoThing)
         }
 
         // Try finding suitable ammoThing for currently set ammo first
-        ammoThing = CompInventory.ammoList.Find(thing => thing.def == selectedAmmo);
+        List<Thing> ammoList = CompInventory.ammoList;
```
Comment (perkinslr) [inline Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs:834]: Why replace this linq with a loop? If it's performance, that's fine.

File: Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs [hunk 2]
```diff
@@ -848,10 +857,23 @@ public bool TryFindAmmoInInventory(out Thing ammoThing)
         // Try finding ammo from different type
         foreach (AmmoLink link in Props.ammoSet.ammoTypes)
         {
-            ammoThing = CompInventory.ammoList.Find(thing => thing.def == link.ammo);
+            ammoThing = null;
+            if (MagAmmoCount > 0 && selectedAmmo != link.ammo)
+            {
+                continue;
+            }
+            for (int i = 0; i < CompInventory.ammoList.Count; i++)
```
Comment (perkinslr) [inline Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs]: Above you got a reference to CompInventory.ammoList, now you're pointing at it indirectly. Either is fine, but it should be consistent.

**Review by perkinslr — DISMISSED** [review]

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
Ran into the issue as described by @Breadbox2k19, where pawns do not correctly switch to other ammo types in their inventory when they run out.

File: Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs (hunk 1 above)
Comment (ViralReaction) [reply Source/CombatExtended/CombatExtended/Comps/CompAmmoUser.cs:834]: Replaced the LINQ with a loop while testing as it is far easier to debug when I was trying to see what was causing the issue. There is the upside that it is slightly faster to execute than LINQ.

**Review by N7Huntsman — CHANGES_REQUESTED** [review]
After the latest changes, we're back to square one with the original issue.

**Review by N7Huntsman — APPROVED** [review]
Disregard my last; loading error on my part.
