### PR TITLE
Riposte Verb_MeleeApplyHediff

### LINKED ISSUE #4312: [Bug]:Vanilla Terrain Verbs (KickMaterialInEyes) cause failure in Riposte logic due to type cast error
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version:1.6.4630 rev466
Combat Extended source (Steam, GitHub, etc.):GitHub_Development
Your operating system:Windows 10 22H2
Your mod list:
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Loading Progress [https:// no link (local mod)]
Loading Progress（简中汉化） [https:// no link (local mod)]
Log After Def Error (Continued) [https:// no link (local mod)]
Better Stacktraces [https:// no link (local mod)]
Visual XML Patches [https:// no link (local mod)]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
Biotech [Official DLC] [https:// no link (local mod)]
Anomaly [Official DLC] [https:// no link (local mod)]
Odyssey [Official DLC] [https:// no link (local mod)]
FSharp.Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2059725183]
XML Extensions [https://steamcommunity.com/sharedfiles/filedetails/?id=2574315206]
XML Extensions简繁中文汉化 [https://steamcommunity.com/sharedfiles/filedetails/?id=2719998589]
Dev In Your Language [https://steamcommunity.com/sharedfiles/filedetails/?id=2142743468]
Dev In Your Language_zh [https://steamcommunity.com/sharedfiles/filedetails/?id=2574656057]
DevelopMode fix [https://steamcommunity.com/sharedfiles/filedetails/?id=2879782112]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
Character Editor 中文化 [https:// no link (local mod)]
Character Editor 简体中文汉化补丁 [https:// no link (local mod)]
Combat Extended [https:// no link (local mod)]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
Humanoid Alien Races zh-pack [https://steamcommunity.com/sharedfiles/filedetails/?id=1783630214]
MoeLotl Race [https:// no link (local mod)]
MoeLotl CE 1.6(Forked) [https:// no link (local mod)]

**Description**
Provide a concise description of the issue or concern. What happened?

When a pawn is standing on terrain that provides a tool/verb (specifically Sand, which provides the vanilla KickMaterialInEyes maneuver), and that pawn triggers a Riposte event in melee combat, CE throws an error and fails to execute the counter-attack.

The vanilla maneuver KickMaterialInEyes uses the "RimWorld.Verb_MeleeApplyHediff(unknown/TerrainVerbs_Axolotl9418_0_KickMaterialInEyes)".
In Verb_MeleeAttackCE.cs, inside the DoParry method, the code attempts to retrieve a riposte verb:
```csharp
Verb_MeleeAttackCE verb = defender.meleeVerbs.TryGetMeleeVerb(caster) as Verb_MeleeAttackCE;
```

**Expected behavior**
What did you expect to happen?

CE should handle non-`Verb_MeleeAttackCE` verbs gracefully during a Riposte.
It should either:
1.  Support vanilla `Verb_MeleeApplyHediff` executions during ripostes.
2.  Or, check if the returned verb is compatible before casting, and if not, simply skip the riposte damage/effect without logging an error (fallback to a standard parry visual).

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

**To reproduce**
1.  Load Rimworld with Core and Combat Extended.
2.  Spawn a colonist pawn equipped with a melee weapon.
3.  Position the pawn on **Sand** terrain (defName: `Sand`).
4.  Spawn a resilient enemy (e.g., a Scyther) to ensure the combat lasts long enough for multiple interactions.
5.  Engage in prolonged melee combat.
    *   *Note:* The specific selection of the "Kick Sand" maneuver by the AI `TryGetMeleeVerb` logic seems to be rare or situational (RNG-dependent). It may not happen immediately.
6.  Wait for the colonist to trigger a **Parry** that results in a **Riposte**.
7.  If the AI happens to select the `KickMaterialInEyes` verb for this specific Riposte action, observe the error log.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

```text
CE failed to get attack verb for riposte from Pawn [PawnName]
[Combat Extended, CombatExtended.dll] CombatExtended.Verb_MeleeAttackCE.DoParry(Verse.Pawn defender, Verse.Thing parryThing, System.Boolean isRiposte, System.Boolean deflected) at CombatExtended\Verbs\Verb_MeleeAttackCE.cs:762
```
log:
https://pastebin.com/6g7RMg8U
DEBUGGER INSPECTION & STACK TRACE:
https://pastebin.com/8RVGxURv

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success. 

Image

### PR DESCRIPTION
**Pull request by ViralReaction**
## Changes

Describe adjustments to existing features made in this merge, e.g.
- Adds type check for Verb_MeleeApplyHediff

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #4312 

## Reasoning

Why did you choose to implement things this way, e.g.
- Very rarely can riposte terrain hediff and should account for this rare vanilla attack.
- So rare either need to wait a very long time or bypass all checks and always force ripostes until it happens to check if code is working

## Alternatives

Describe alternative implementations you have considered, e.g.
- Occasional errors

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

File: Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs [hunk 1]
```diff
@@ -756,15 +756,21 @@ protected virtual void DoParry(Pawn defender, Thing parryThing, bool isRiposte =
...
-                Verb_MeleeAttackCE verb = defender.meleeVerbs.TryGetMeleeVerb(caster) as Verb_MeleeAttackCE;
-                if (verb == null)
+                Verb verb = defender.meleeVerbs.TryGetMeleeVerb(caster);
+                Verb_MeleeAttackCE ceVerb = verb as Verb_MeleeAttackCE;
+                if (verb is Verb_MeleeApplyHediff hediffVerb)
+                {
+                    hediffVerb.ApplyMeleeDamageToTarget(caster);
+                    sound = hediffVerb.SoundHitPawn();
+                }
+                if (ceVerb == null)
```
Comment (mszabo-wikia) [inline Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs]: won't we still hit this branch for the `verb is Verb_MeleeApplyHediff hediffVerb` case? we might need to wrap it into an else

Comment (ViralReaction) [reply Source/CombatExtended/CombatExtended/Verbs/Verb_MeleeAttackCE.cs]: Good catch, made else if

**Review by N7Huntsman — APPROVED** [review]
