### PR TITLE
Fix Toggle Saving

### LINKED ISSUE #4214: [Bug]: CIWS Hold Fire gizmos reset their state on save load
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: CIWS Hold Fire gizmos reset their state on save load

**Specifications**
Please provide the following.

Rimworld version: 1.6
Combat Extended version: 1.6 dev
Combat Extended source (Steam, GitHub, etc.): dev
Your operating system: windows
Your mod list: minimal

**Description**
Provide a concise description of the issue or concern. What happened?
Every time you load in a save, your hold fire settings for CIWS turrets get reset for both "Hold fire projectiles" and "Hold fire skyfallers" gizmos.

**Expected behavior**
What did you expect to happen?
On save load, they retain their previous state

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
1. Build KPV
2. Toggle "hold fire skyfallers" ON
3. Save
4. Load save and check toggle state

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

### PR DESCRIPTION
**Pull request by ViralReaction**
## Additions

Describe new functionality added by your code, e.g.
- Adds saving of HoldFire bool on the verb

## References

Links to the associated issues or other related pull requests, e.g.
- Closes #4214

## Reasoning

Why did you choose to implement things this way, e.g.
- Needs saving and was able to save on verb

## Alternatives

Describe alternative implementations you have considered, e.g.
- Suffer

## Testing

Check tests you have performed:
- [x] Compiles without warnings
- [x] Game runs without errors
- [x] (For compatibility patches) ...with and without patched mod loaded
- [x] Playtested a colony (specify how long)

### CODE REVIEW

File: Source/CombatExtended/CombatExtended/Comps/CompVerbDisabler.cs [hunk 1]
```diff
@@ -9,36 +9,74 @@
...
+        var command = new Command_Toggle()
+        {
+            defaultDesc = _disableableVerbCache.HoldFireDesc.Translate(),
+            defaultLabel = _disableableVerbCache.HoldFireLabel.Translate(),
+            icon = _disableableVerbCache.HoldFireIcon,
+            isActive = () => _disableableVerbCache.HoldFire,
+            toggleAction = ToggleHoldFire,
+
+        };
+        yield return command;
```
Comment (mszabo-wikia) [inline Source/CombatExtended/CombatExtended/Comps/CompVerbDisabler.cs]: we now return only one gizmo instead of one per verb, is this because in practice there's always just one?

File: Source/CombatExtended/CombatExtended/Comps/CompVerbDisabler.cs [hunk 2]
```diff
@@ -9,36 +9,74 @@
...
+        }
+        foreach (var verb in verbs)
+        {
+            if (verb is not IVerbDisableable disableableVerb)
+            {
+                continue;
+            }
+            _disableableVerbCache = disableableVerb;
+            _disableableVerbCache.HoldFire = _holdFire;
+        }
```
Comment (mszabo-wikia) [inline Source/CombatExtended/CombatExtended/Comps/CompVerbDisabler.cs]: see note below, if intended, we could `break` here to make it explicit

Comment (ViralReaction) [reply Source/CombatExtended/CombatExtended/Comps/CompVerbDisabler.cs]: I believe in practice we only have one as of right now. Probably best to break until it changes unless we want the functionality baked it now.
